#ifndef _LIBDLG_H_
#define _LIBDLG_H_

class PieceInfo;

// =============================================================================
// LibraryDialog class

enum
{
	LC_LIBDLG_FILE_RESET,
	LC_LIBDLG_FILE_OPEN,
	LC_LIBDLG_FILE_SAVE,
	LC_LIBDLG_FILE_SAVEAS,
	LC_LIBDLG_FILE_PRINTCATALOG,
	LC_LIBDLG_FILE_RETURN,
	LC_LIBDLG_FILE_CANCEL,
	LC_LIBDLG_CATEGORY_NEW,
	LC_LIBDLG_CATEGORY_REMOVE,
	LC_LIBDLG_CATEGORY_EDIT,
	LC_LIBDLG_CATEGORY_RESET,
	LC_LIBDLG_GROUP_INSERT,
	LC_LIBDLG_GROUP_DELETE,
	LC_LIBDLG_GROUP_EDIT,
	LC_LIBDLG_GROUP_MOVEUP,
	LC_LIBDLG_GROUP_MOVEDOWN,
};

class LibraryDialog
{
public:
   bool HandleCommand(int id);
};

#endif // _LIBDLG_H_
